### ISSUE TITLE
[Suggestion] Format return values of checkFriendship() with underscores

### ISSUE THREAD

**Issue by ghost** [merodiro/Friendships#17]
## Detailed description

This is a minor enhancement/suggestion

same user > same_user
not friends > not_friends

## Context

One benefit is simply the semantics of it, these values are *sort of like constants* returned by a function. The underscores could indicate that they aren't just some random strings to display but to be used in other logic.

Another minor but tangible benefit of this is that they make the text easier to select and copy-paste to different files.

For example when you double click these values (or use CTRL+D in Sublime or any word selection function in other editors), only one word will be selected because they are separated by a space.

With underscores, the editor will consider them as *one word*.

Yes this is very minor but it does provide some convenience if you write a lot of friendship related functionality.

## Possible implementation

x

## Your environment

x

**Comment by ghost** [comment]
@merodiro If you agree with this suggestion I will change this myself and submit a pull request

**Comment by merodiro** [comment]
sorry for not responding in last days because of my exams.
I like the suggestion, I will change it.

**Comment by merodiro** [comment]
thank you for your suggestion.
